services:
  ui:
    build:
      context: "."
      target: "builder"
      args:
        - "env=dev"
    restart: "on-failure"
    ports: !override
      # 5173 is Vite dev server's default port
      - "80:5173"
    volumes:
      - "./src:/app/src:ro"
      - "./index.html:/app/index.html:ro"
      - "./.eslintrc.cjs:/app/.eslintrc.cjs:ro"
      - "./vite.config.ts:/app/vite.config.ts:ro"
      - "./tsconfig.json:/app/tsconfig.json:ro"
      - "./tsconfig.app.json:/app/tsconfig.app.json:ro"
      - "./tsconfig.node.json:/app/tsconfig.node.json:ro"
