services:
  ui:
    build:
      context: "."
      target: "builder"
      args:
        - "env=dev"
    restart: "on-failure"
    ports:
      # 5173 is Vite dev server's default port
      - "80:5173"
    volumes:
      - "./src:/app/src:ro"
      - "./index.html:/app/index.html:ro"
      - "./.eslintrc.cjs:/app/.eslintrc.cjs:ro"
